"""empty message

Revision ID: 056790487a56
Revises: 86faf81ff356
Create Date: 2021-02-22 01:46:59.481383

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '056790487a56'
down_revision = '86faf81ff356'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Venue', 'past_shows_count')
    op.drop_column('Venue', 'upcoming_shows_count')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Venue', sa.Column('upcoming_shows_count', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('Venue', sa.Column('past_shows_count', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
