"""empty message

Revision ID: 414f5eb01e44
Revises: 056790487a56
Create Date: 2021-02-22 04:48:54.617182

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '414f5eb01e44'
down_revision = '056790487a56'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Artist', 'upcoming_shows_count')
    op.drop_column('Artist', 'past_shows_count')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Artist', sa.Column('past_shows_count', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('Artist', sa.Column('upcoming_shows_count', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
